// Edit this placeholder text as necessary to describe the deployment options.

This Quick Start provides the following deployment options:

* https://fwd.aws/XExbV[Deploy {partner-product-short-name} into a new VPC^]. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure components. It then deploys {partner-product-name} into this new VPC.
* https://fwd.aws/aDgWD[Deploy {partner-product-short-name} into an existing VPC^]. This option provisions {partner-product-name} in your existing AWS infrastructure.

This Quick Start provides separate templates for these options. It also lets you configure Classless Inter-Domain Routing (CIDR) blocks, instance types, and {partner-product-short-name} settings.

=== Authentication

In addition to the two deployment options, there is one authentication option for deployment.

** Deploy with authorized Account ID, Username, and Password (Not MFA compatible)

You will need to choose one method or the other. If you are unsure of how to create an Installation Token or API Token/Key, see link:#_creating_an_installation_token[Creating an Installation Token] in this guide for steps or contact your administrator.