// This contains list of all useful infromation

== Other Useful Information

=== Bastion host
AWS EKS quickstart deploys a bastion virtual machine for the administrator to run kubectl commands against the kubernetes cluster. 

=== Pod Autoscaling
AWS EKS quickstart deploys kubernetes horizontal pod autoscaling with target CPU utilization 60%. If the average utilization of all the pods go beyond 60%, pods will be auto scaled.

=== Node Autoscaling
AWS EKS quickstart deploys by default 3 nodes with maximum capacity =3 in the autoscaling group. To autoscale the nodes , we need to increase the maximum capacity values.

=== Upgrade Boomi Molecule Docker Image 
Please follow the steps to upgrade the molecule image in the existing deployment :-

. Login to bastion host .
. Run the kubectl command -  *kubectl get statefulset -n eks-boomi-molecule -o yaml > statefulset.yaml*.
. Edit statefulset.yaml and update boomi molecule image
. Run kubectl command - *kubectl apply -f statefulset.yaml -n eks-boomi-molecule*.

This will automatically perform a rolling restart of the statefulset.

=== Steps to Configure SSL Certificate to Load balancer

Application Load Balancer:

.	Go to application load balancer 
.	Open listeners tab and click on add listener 
.	Select HTTPS Protocol 
.	Select Forward action and map to correct target group
.	Select valid SSL certificate from ACM
.	Open security group attached to ALB and add HTTPS -> 0.0.0.0/0 inbound rule.
.	Go to Route 53 domain name and add new A record with same name as SSL certificate name
.	Edit record name and route traffic to ALB

Network Load Balancer:

.	Go to network load balancer 
.	Open listeners tab and edit 443 listener
.	Select TLS Protocol 
.	Select Forward action and map to correct target group
.	Select valid SSL certificate from ACM 
.	Go to Route 53 domain name and add new A record with same name as SSL certificate name
.	Edit record name and route traffic to NLB


